version: "3"
services:
  api:
    build: .
    volumes:
      - .:/realworld_api
    ports:
      - 3003:3000
    environment:
      TZ: Asia/Tokyo
    stdin_open: true
    tty: true
    networks:
      - mynetwork

volumes:
  data-volume:

networks:
  mynetwork:
    external: true
