version: "3"
services:
  api:
    build: .
    volumes:
      - .:/realworld_api
    ports:
      - 3003:3000
    environment:
      TZ: Asia/Tokyo
    stdin_open: true
    tty: true

volumes:
  data-volume:
